export * from './auth.schema';
export * from './base.schema';
export * from './subject.schema'
export * from './course.schema'
export * from './topic.schema';
export * from './lesson.schema';
export * from './content.schema';
export * from './exercise.schema';
export * from './university.schema';